# Remember Vectors and Matrices?
In your previous math courses, you learned the concept of vectors and matrices. In CSMODEL, we would also be using vectors and matrices. However, instead of using pen and paper, we are going to use Python to define vectors and matrices and perform operations on them. In this Notebook, we will see how we can represent vectors and matrices using NumPy, a useful package for Python for mathematical operations.

Our Notebooks in CSMODEL are designed to be guided learning activities. To use them, simply go through the cells from top to bottom, following the directions along the way. If you find any unclear parts or mistakes in the Notebooks, email your instructor.

## NumPy
**NumPy** is a library for the Python programming language. It contains a large collection of mathematical functions, as well as convenient data structures to represent vectors and matrices. To use NumPy, we first need to import it.

In [1]:
import numpy as np

Now, we can access the functionalities of NumPy as `np`.

## Creating Vectors and Matrices

A vector is a list of numbers, which could be in a row or in a column. To create vectors in NumPy, we simply use the `np.array()` function. To create this vector:
\begin{equation*}
\begin{bmatrix}
2 & 4 & 6
\end{bmatrix}
\end{equation*}

In [2]:
v = np.array([2, 4, 6])
v

array([2, 4, 6])

The vector above is a 1-dimensional vector. However, sometimes, you would want to define a row vector or a column vector. In this case, you can use a 2-dimensional array to initialize the vector.

To create this row vector:
\begin{equation*}
\begin{bmatrix}
2 & 4 & 6
\end{bmatrix}
\end{equation*}

In [3]:
v = np.array([[2, 4, 6]])
v

array([[2, 4, 6]])

To create this column vector:
\begin{equation*}
\begin{bmatrix}
2 \\
4 \\
6
\end{bmatrix}
\end{equation*}

In [4]:
v = np.array([[2],
              [4],
              [6]])
v

array([[2],
       [4],
       [6]])

A matrix is a rectangular array arranged in rows and columns. To create matrices in NumPy, we also use the `np.array()` function.

To create this matrix:
\begin{equation*}
\begin{bmatrix}
1 & 2  & 3  & 4  \\
5 & 6  & 7  & 8  \\
9 & 10 & 11 & 12
\end{bmatrix}
\end{equation*}

In [5]:
A = np.array([[1,  2,  3,  4],
              [5,  6,  7,  8],
              [9, 10, 11, 12]])
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

To create this matrix:
\begin{equation*}
\begin{bmatrix}
10 &  20 \\
30 &  40 \\
50 &  60 \\
70 &  80 \\
90 & 100
\end{bmatrix}
\end{equation*}

In [6]:
A = np.array([[10,  20],
              [30,  40],
              [50,  60],
              [70,  80],
              [90, 100]])
A

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

You can use `np.zeroes()` to create a vector or matrix full of 0s. Note that the parameter of this function is a tuple representing the shape of the vector or matrix. In NumPy, shape just refers to the dimensions of the array.

In [7]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

You can also use `np.ones()` to create a vector or matrix full of 1s.

In [8]:
np.ones((7, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Indexing

You can index a specific element from the vector using array-style indexing. Note the use of negative indices as discussed in the previous Notebook. You may play around the indices here to experiment.

Initialize vector `v` and matrix `A`.

In [9]:
v = np.array([10, 20, 30, 40, 50, 60, 70, 80])
A = np.array([[ 2,  4,  6],
              [ 8, 10, 12],
              [14, 16, 18]])

Get the element in index 2 of vector `v`.

In [10]:
v[2]

30

Get the element in the second to the last index of vector `v`.

In [11]:
v[-2]

70

Get the element in row index 1 and column index 2 of matrix `A`.

In [12]:
A[1, 2]

12

Get the element in the last row and last column of matrix `A`.

In [13]:
A[-1, -1]

18

You can select an entire row or column of a matrix by using slicing techniques on either dimension.

Initialize matrix `A`.

In [14]:
A = np.array([[ 2,  4,  6],
              [ 8, 10, 12],
              [14, 16, 18]])

Select the first row of matrix `A`.

In [15]:
A[0, :]

array([2, 4, 6])

Select the second column of matrix `A`.

In [16]:
A[:, 1]

array([ 4, 10, 16])

Select the last column of matrix `A`.

In [17]:
A[:, -1]

array([ 6, 12, 18])

And by extension, you can select any subset of a matrix by using slicing operations. The cell below has no output, but be sure to execute it because the next cells use the variables created here.

In [18]:
A = np.array([[ 2,  4,  6,  8, 10],
              [12, 14, 16, 18, 20],
              [22, 24, 26, 28, 30],
              [32, 34, 36, 38, 40],
              [42, 44, 46, 48, 50]])

Select the first 3 rows of matrix `A`.

In [19]:
A[:3, :]

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

Select the last 2 rows of matrix `A`.

In [20]:
A[-2:, :]

array([[32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

Select the last 3 columns of matrix `A`.

In [21]:
A[:, -3:]

array([[ 6,  8, 10],
       [16, 18, 20],
       [26, 28, 30],
       [36, 38, 40],
       [46, 48, 50]])

Select the $3\times3$ sub-matrix from the top left corner of matrix `A`.

In [22]:
A[0:3, 0:3]

array([[ 2,  4,  6],
       [12, 14, 16],
       [22, 24, 26]])

**Practice!** Select the number 14 from the matrix `X`.

In [24]:
X = np.array([[ 2,  4,  6],
              [ 8, 10, 12],
              [14, 16, 18]])

# Write your code here
X[2][0]

14

**Practice!** Select the third row from the matrix `Y` (the one with 1s).

In [37]:
Y = np.array([[0, 0, 0, 0],
              [0, 0, 0, 0],
              [1, 1, 1, 1],
              [0, 0, 0, 0],
              [0, 0, 0, 0],
              [0, 0, 0, 0]])

# Write your code here
Y[2,:]

array([1, 1, 1, 1])

**Practice!** Select the first three columns from matrix `C`, but exclude the last row which only contains zeroes.

In [39]:
C = np.array([[ 1,  3,  5,  7,  9],
              [11, 13, 15, 17, 19],
              [21, 23, 25, 27, 29],
              [ 0,  0,  0,  0,  0]])

# Write your code here
C[:-1,:3]

array([[ 1,  3,  5],
       [11, 13, 15],
       [21, 23, 25]])

## Shape

To check the dimensions of a NumPy array, use the `np.shape()` function. In NumPy, shape simply means the dimension of the array, and is represented as a tuple.

Vector with one axis.

In [40]:
v = np.array([1, 2, 3, 4, 5])
np.shape(v)

(5,)

Vector with two axes.

In [41]:
v = np.array([[1, 2, 3, 4, 5]])
np.shape(v)

(1, 5)

Vector with two axes.

In [42]:
v = np.array([[1],
              [2],
              [3]])
np.shape(v)

(3, 1)

Matrix with 2 rows and 3 columns.

In [43]:
A = np.array([[1, 2, 3],
              [1, 2, 3]])
np.shape(A)

(2, 3)

Matrix with 6 rows and 4 columns.

In [44]:
A = np.array([[1, 2, 3, 4],
              [1, 2, 3, 4],
              [1, 2, 3, 4],
              [1, 2, 3, 4],
              [1, 2, 3, 4],
              [1, 2, 3, 4]])
np.shape(A)

(6, 4)

## Reshape
The `reshape()` function allows you to change the dimensions of an existing vector or matrix by passing a tuple representing the new shape.

Initialize vector `original`.

In [45]:
original = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]])

Reshape vector `original` to a matrix with 4 rows and 4 columns.

In [46]:
original.reshape((4, 4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

Reshape vector `original` to a matrix with 2 rows and 8 columns.

In [47]:
original.reshape((2, 8))

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

The example below will yield an error because the new shape is not compatible with the original shape.

In [48]:
original.reshape((5, 3))

ValueError: cannot reshape array of size 16 into shape (5,3)

You can reshape not only vectors, but also matrices.

Initialize matrix `original`.

In [49]:
original = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8]])

Reshape matrix `original` to a vector with two axes.

In [50]:
original.reshape((1, 8))

array([[1, 2, 3, 4, 5, 6, 7, 8]])

Reshape matrix `original` to a matrix with 4 rows and 2 columns.

In [51]:
original.reshape((4, 2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

**Practice!** Reshape the vector `v` to come up with a matrix where the first (leftmost) column contains only 1s.

In [52]:
v = np.array([1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0])

# Write your code here
v.reshape((3,4))

array([[1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0]])

## Concatenating Vectors and Matrices

The `np.concatenate()` function is a flexible function that can be used to combine mutliple vectors and matrices together. This comes in handy when you need to add a row or a column to an existing matrix.

In [53]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6]])

np.concatenate((A, B))

array([[1, 2],
       [3, 4],
       [5, 6]])

If you specify an `axis` parameter and set it to 1, the concatenation will be performed on the column instead of the row.

In [54]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5],
              [6]])

np.concatenate((A, B), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

Note that for the `np.concatenate()` function to work, the number of dimensions should be the same. That is, you cannot concatenate a 2-dimensional matrix with a 1-dimensional vector.

## Copying Vectors and Matrices

If you want to make a copy of an existing vector or matrix, you can use the `np.copy()` function. Note that simply assigning the vector or matrix to another variable will not copy it. Instead, both variables will hold a reference to the same vector or matrix.

If you simply assign to another variable, the vector is not copied.

In [55]:
A = np.array([1, 2, 3, 4])
B = A

A[1] = 9

print(A)
print(B)

[1 9 3 4]
[1 9 3 4]


If you use the `np.copy()` function, then a copy of the vector or matrix is assigned to the variable.

In [56]:
A = np.array([1, 2, 3, 4])
B = np.copy(A)

A[1] = 9

print(A)
print(B)

[1 9 3 4]
[1 2 3 4]


## Element-Wise Operations

You can perform element-wise operations on a vector / matrix and a scalar. This means applying the operation to each element of the vector or matrix.

Check if the value of each element inside the vector `v` is greater than scalar 3.

In [57]:
v = np.array([5, 1, 4, 6, 3, 7, 5, 3, 2])
v > 3

array([ True, False,  True,  True, False,  True,  True, False, False])

Multiply the value of each element inside matrix `A` with scalar 2.

In [58]:
A = np.array([[1, 2, 3, 4],
              [4, 3, 2, 1]])
A * 2

array([[2, 4, 6, 8],
       [8, 6, 4, 2]])

You can also perform element wise operations on two vectors / matrices of the same shape. This means applying the operations on the corresponding elements of the two operands.

Check if the value inside vector `v` is equal to the corresponding value inside vector `w`.

In [59]:
v = np.array([1, 2, 3, 4, 5, 6, 7, 8])
w = np.array([3, 2, 4, 1, 5, 8, 7, 6])
v == w

array([False,  True, False, False,  True, False,  True, False])

Raise the value inside matrix `A` to the corresponding value in matrix `B`.

In [60]:
A = np.array([[2, 2],
              [2, 2]])
B = np.array([[1, 2],
              [3, 4]])
A ** B

array([[ 2,  4],
       [ 8, 16]])

**Practice!** Complete the definition for the matrix `beta` such that the result of adding `alpha` and `beta` is a matrix containing only zeros.

In [64]:
alpha = np.array([[3, 2, 1],
                  [6, 5, 4],
                  [9, 8, 7]])
beta = np.array([[-3, -2, -1],
                [-6, -5, -4],
                [-9, -8, -7]])  # define the beta matrix here



alpha + beta

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## Matrix Multiplication and Transpose

There is an important operation in linear algebra called [matrix multiplication](https://www.mathsisfun.com/algebra/matrix-multiplying.html) (also known as dot product). In NumPy, we can perform matrix multiplication using the `np.dot()` function. Note that despite the term "multiplication", do not use the `*` operator to perform matrix multiplication because this will result in element-wise multiplication.

Perform matrix operation between matrix `A` and matrix `B`.

In [65]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[ 7,  8],
              [ 9, 10],
              [11, 12]])
np.dot(A, B)

array([[ 58,  64],
       [139, 154]])

Alternatively, since Python 3.5+ you can use the `@` operator.

In [66]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[ 7,  8],
              [ 9, 10],
              [11, 12]])
A @ B

array([[ 58,  64],
       [139, 154]])

Please remember from your math classes that:

- Matrix multiplication is not commutative. Thus, the order of the operands matter.
- For the operation to be defined, the number of columns of the first operand should match the number of rows of the second operand.

To perform a [transpose](https://www.mathsisfun.com/definitions/transpose-matrix-.html) operation on a matrix, we can use the `np.transpose()` function.

In [67]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
np.transpose(A)

array([[1, 4],
       [2, 5],
       [3, 6]])

Alternatively, you may also use the `T` property to get the transposed matrix.

In [68]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

**Practice!** If you take a row vector and perform matrix multiplication with its transpose, you will get the sum of the squares of each element in the original vector. Verify this by performing this operation on the given vector `v`. This should result into $1^2 + 2^2 + 3^2 + 4^2 = 30$.

In [69]:
v = np.array([[1, 2, 3, 4]])

# Write your code here
np.dot(v, v.T)

array([[30]])

## Vectorizing Functions

If you have a function that normally operates on a single data point, you can vectorize it so that it will be applied to every element of a vector or matrix. For example, let's say we have this function which counts the number of factors of an integer:

In [70]:
def count_factors(n):
    count = 0
    for i in range(1, n + 1):
        if n % i == 0:
            count = count + 1
    return count

Then, let's say we have a vector `v`:

In [71]:
v = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]])

Let's say we want to count the number of factors of each element in `v`. To do this, we can first vectorize the `count_factors` function using the `np.vectorize()` function.

In [72]:
count_factors_vectorized = np.vectorize(count_factors)

Then, we can pass the vector instead of a single value.

In [73]:
count_factors_vectorized(v)

array([[1, 2, 2, 3, 2, 4, 2, 4, 3, 4, 2, 6, 2, 4, 4]])

This will also work on matrices.

In [74]:
A = np.array([[10, 20],
              [30, 40]])
count_factors_vectorized(A)

array([[4, 6],
       [8, 8]])

**Practice!** Create a function that returns `True` if the integer is even or `False` if the integer is odd. Vectorize this function so that it could be applied to the vector `list`.

In [76]:
list = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])

def is_even(n):
    # Write your code here
    if n % 2 == 0:
        return True
    else:
        return False

# Vectorize the function
np.vectorize(is_even)
# Apply it to the list vector
list = np.vectorize(is_even)
list

## Basic Mathematical Operations in NumPy

NumPy provides some common functions for mathematical operations.

Initialize vector `v`.

In [77]:
v = np.array([12, 8, 20, 4, 16])

Get the maximum value in vector `v`.

In [78]:
np.max(v)

20

Get the minimum value in vector `v`.

In [79]:
np.min(v)

4

Get the sum of all values in vector `v`.

In [80]:
np.sum(v)

60

If you have a matrix, you can specify the `axis` parameter to specify if the operations are to be performed per column (0) or per row (1).

Initialize matrix `A`.

In [81]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

Get the sum per column in matrix `A`.

In [82]:
np.sum(A, axis=0)

array([12, 15, 18])

Get the sum per row in matrix `A`.

In [83]:
np.sum(A, axis=1)

array([ 6, 15, 24])

Get the sum of all elements in matrix `A`.

In [84]:
np.sum(A)

45

**Practice!** Write code that adds a row to the matrix `grid` containing the highest value in each column. For example, given the matrix:
\begin{equation*}
\begin{bmatrix}
2 & 3 & 1 & 6 \\
4 & 9 & 2 & 7 \\
3 & 3 & 5 & 1
\end{bmatrix}
\end{equation*}
The resulting matrix should be:
\begin{equation*}
\begin{bmatrix}
2 & 3 & 1 & 6 \\
4 & 9 & 2 & 7 \\
3 & 3 & 5 & 1 \\
4 & 9 & 5 & 7
\end{bmatrix}
\end{equation*}

**Note**: `max` returns a 1-dimensional vector, so might need to reshape it to a 2-dimensional row vector before you can concatenate it to the original matrix.

In [85]:
grid = np.array([[2, 3, 1, 6],
                 [4, 9, 2, 7],
                 [3, 3, 5, 1]])

# Write your code here
max_values = np.max(grid, axis=0)
grid = np.vstack([grid, max_values])
grid

array([[2, 3, 1, 6],
       [4, 9, 2, 7],
       [3, 3, 5, 1],
       [4, 9, 5, 7]])

## What's Next?

This is just the tip of the iceberg for things that you can accomplish with NumPy. As we go through the succeeeding activities in CSMODEL, we will be covering more techniques and functionalities in NumPy. Furthermore, we encourage you not to limit yourselves with the examples presented in this Notebook, but to explore and try out stuff on your own.